# Generated by Django 6.0.1 on 2026-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='microphones',
            field=models.ManyToManyField(blank=True, to='project.microphone'),
        ),
    ]
